### PR TITLE
Us 07 battle result

### PR DESCRIPTION
**Pull request by thocle86**
I made 3 commits on this US:
* Added battle function in game controller + replacing the level variable with strength + inserting the deleteAll function in AbstractManager
* Adding PDO exceptions to the TroopManager and EnemyManager classes + Added battle result window
* Bug fix on the battle display, we were losing all the time

### CODE REVIEW

**Review by maxime-auneau — DISMISSED** [review]
ok

**Review by FranciscoKevin — DISMISSED** [review]
ok

**Review by RomainClair — CHANGES_REQUESTED** [review]
It seems you shouldn't have troops or enemy with no name/strength/tiredness or castle with no name but now almost everything has a default null in you database.

The style.css is invalid

You would probably have been better to not modify your framework (AbstractManager).
if you want a superclass for all your managers, you could have a new class inherited by your managers and which extends the abstract manager

**Review by maxime-auneau — DISMISSED** [review]
ok

**Review by FranciscoKevin — DISMISSED** [review]
ok

**Review by maxime-auneau — APPROVED** [review]
ok

**Review by FranciscoKevin — APPROVED** [review]
Du coup la bdd c'est bon.

**Review by RomainClair — APPROVED** [review]

**Pull request merged**
